framework:
    secret: '%env(APP_SECRET)%'
    http_method_override: true # Some templates post a _method override

    # Note that the session will be started ONLY if you read or write from it.
    session: true

    #esi: true
    #fragments: true

