twig:
    file_name_pattern: '*.twig'
    form_themes:
      - form_div_layout.html.twig
      - bootstrap_4_layout.html.twig
    globals:
        app_domain: '%app.domain%'

when@test:
    twig:
        strict_variables: true
