language: minimal

services:
  - docker

script:
  - docker-compose up -d mysql
  - sleep 30
  - docker-compose run php bash -c "mkdir -p build/logs && php bin/phpunit --coverage-clover build/logs/clover.xml && php vendor/bin/php-coveralls"
