language: minimal

services:
  - docker

script:
  - docker-compose run --rm php composer install
  - docker-compose up -d mysql
  - sleep 30
  - docker-compose run php php bin/console doctrine:migrations:migrate --no-interaction
  - docker-compose run --rm php php bin/phpunit --coverage-clover clover.xml
  - docker-compose run --rm php php vendor/bin/coverage-check clover.xml 16
