version: '3.7'

volumes:
  mysql:
  composer:
  statements:

services:

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_USER: $MYSQL_USER
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_PASSWORD: $MYSQL_PASSWORD
    volumes:
      - mysql:/var/lib/mysql

  adminer:
    image: adminer:4.7.6-standalone
    ports:
      - 8080:8080
    depends_on:
      - mysql

  php:
    build:
      context: ./
      dockerfile: ./docker/build/Dockerfile-php
    environment:
      APP_DOMAIN: localhost
    volumes:
      - ./:/var/www/html
      - statements:/var/statements
      - composer:/root/.composer
    depends_on:
      - mysql

  account_statement_parser:
    image: ovski/account-statement-parser
    volumes:
      - statements:/var/statements

  web_socket:
    build:
      context: ./
      dockerfile: ./docker/build/Dockerfile-php
    volumes:
      - ./:/var/www/html
      - composer:/root/.composer
    depends_on:
      - mysql
    command: php bin/console app:start-web-socket-server

  nginx:
    image: nginx:1.16.1
    volumes:
      - ./:/var/www/html
      - ./docker/conf/vhost.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    ports:
      - 80:80

networks:

  default:
    name: expenses
    external: true
