version: '3.7'

volumes:
  mysql:
  statements:

services:

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_USER: expenses_categorizer
      MYSQL_DATABASE: expenses_categorizer
      MYSQL_PASSWORD: expenses_categorizer
    volumes:
      - mysql:/var/lib/mysql

  php:
    image: ovski/expenses-categorizer-php:v1.1.2
    environment:
      APP_DOMAIN: your.domain.com
      APP_ENV: prod
      APP_SECRET: whatever
      LOCALE: en
      MYSQL_USER: expenses_categorizer
      MYSQL_DATABASE: expenses_categorizer
      MYSQL_PASSWORD: expenses_categorizer
      MYSQL_HOST: mysql
      RUN_MIGRATIONS: 'true'
      VERSION: v1.1.2
    volumes:
      - statements:/var/statements
    depends_on:
      - mysql

  account_statement_parser:
    image: ovski/account-statement-parser:v1.0.5
    volumes:
      - statements:/var/statements

  web_socket:
    image: ovski/expenses-categorizer-php:v1.1.2
    depends_on:
      - mysql
      - php
    command: php bin/console app:start-web-socket-server
    environment:
      APP_DOMAIN: your.domain.com
      APP_ENV: prod
      APP_SECRET: whatever
      LOCALE: en
      MYSQL_USER: expenses_categorizer
      MYSQL_DATABASE: expenses_categorizer
      MYSQL_PASSWORD: expenses_categorizer
      MYSQL_HOST: mysql
      VERSION: v1.1.2
  nginx:
    image: ovski/expenses-categorizer-nginx:v1.1.2
    depends_on:
      - php
    ports:
      - 80:80
