version: '3.7'

volumes:
  mysql:
  composer:
  statements:

services:

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_USER: expenses_categorizer
      MYSQL_DATABASE: expenses_categorizer
      MYSQL_PASSWORD: expenses_categorizer
    volumes:
      - mysql:/var/lib/mysql

  adminer:
    image: adminer:4.7.6-standalone
    ports:
      - 8080:8080
    depends_on:
      - mysql

  php:
    build:
      context: ./
      dockerfile: ./docker/build/php/Dockerfile
    environment:
      APP_DOMAIN: localhost
      MYSQL_USER: expenses_categorizer
      MYSQL_DATABASE: expenses_categorizer
      MYSQL_PASSWORD: expenses_categorizer
      MYSQL_HOST: mysql
      APP_ENV: dev
      LOCALE: en
      RUN_MIGRATIONS: 'true'
    volumes:
      - ./:/var/www/html
      - statements:/var/statements
      - composer:/root/.composer
    depends_on:
      - mysql

  account_statement_parser:
    image: ovski/account-statement-parser
    volumes:
      - statements:/var/statements

  web_socket:
    build:
      context: ./
      dockerfile: ./docker/build/php/Dockerfile
    volumes:
      - ./:/var/www/html
      - composer:/root/.composer
    depends_on:
      - mysql
      - php
    command: php bin/console app:start-web-socket-server
    environment:
      MYSQL_USER: expenses_categorizer
      MYSQL_DATABASE: expenses_categorizer
      MYSQL_PASSWORD: expenses_categorizer
      MYSQL_HOST: mysql
      APP_ENV: dev
      LOCALE: en

  nginx:
    build:
      context: ./
      dockerfile: ./docker/build/nginx/Dockerfile
    volumes:
      - ./:/var/www/html
    depends_on:
      - php
    ports:
      - 80:80
