on:
  push:
    branches:
      - 'master'

jobs:
  run-tests:
    environment: ci
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repository
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push the nginx image
        uses: docker/build-push-action@v2
        with:
          context: ./docker/build/nginx/Dockerfile
          push: true
          tags: ovski/expenses-categorizer-nginx:latest

      - name: Build and push the php image
        uses: docker/build-push-action@v2
        with:
          context: ./docker/build/php/Dockerfile
          push: true
          tags: ovski/expenses-categorizer-php:latest
